# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=10)),
                ('odoo_hq_id', models.IntegerField()),
                ('odoo_parent_id', models.IntegerField()),
                ('street1', models.CharField(max_length=255)),
                ('street2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('zip_code', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('end_of_probation', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=10)),
                ('account_no', models.CharField(max_length=15)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
    ]
