# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20160323_0654'),
        ('hr', '0002_auto_20160421_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='odoo_hq_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='hq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.HQ'),
        ),
    ]
