#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Django settings for intranet project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_DIR = os.path.dirname(__file__)
PROJECT_PATH = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'templates')
LOGIN_URL = 'home.views.intra_login' 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'hrfv6)yja1_udlpjcw+^kz$pdo=f+d=5b&_^94e^hcb=f_gb42'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = []

# Session related settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SECURITY_WARN_AFTER = 1200
SESSION_SECURITY_EXPIRE_AFTER = 1080

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'crispy_forms',
    'session_security',

    'home',
    'marketing',
    'hr',
    ]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'session_security.middleware.SessionSecurityMiddleware',
    ]

ROOT_URLCONF = 'intranet.urls'

#TEMPLATE_DIRS = (
    # Put strings here, like "/home/html/django_templates" or "C:/www/django/templates".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
#    TEMPLATE_PATH,
#)

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [
		TEMPLATE_PATH,
		],
    'APP_DIRS': True,
    'OPTIONS': {'context_processors': ['django.template.context_processors.debug'
                , 'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
		'django.core.context_processors.request',
                ]},
    }]

WSGI_APPLICATION = 'intranet.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
        'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': 'DeltasPharma_INTRA',
                'USER': 'odoo',
                'PASSWORD': 'Deltas@2015',
                'HOST': 'localhost',
                'PORT': '',
        },
	'odoo_data': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': 'DeltasPharma',
		'USER': 'odoo',
		'PASSWORD': 'Deltas@2015',
		'HOST': '128.199.120.195',
		'PORT': '',
	}
    }

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = \
    [{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
     },
     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'
     },
     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'
     },
     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'
     }]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


# For Media Files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Global Settings and constants
GLOBAL_SETTINGS = {
    'URL': 'http://128.199.120.195:8069',
    'DB': 'DeltasPharma_QA',
    'USER_NAME': 'admin',
    'PASSWORD': 'Deltas@2015',
    'UID': 1,
    # Email settings
    'TO_IT': 'support@aitspl.com',
    'TO_HR': 'dheeraj.agarwal@deltaspharma.com',
    'TO_PPP': 'dilip.jain@deltaspharma.com',
    'TO_MARKETING': 'dilip.jain@deltaspharma.com'
}
# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'deltaspharma@gmail.com' 
EMAIL_HOST_PASSWORD = 'deltas123' 
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
