# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_chemist_id', models.IntegerField()),
                ('chemist_name', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=200, null=True)),
                ('street2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('odoo_hq_id', models.IntegerField()),
                ('odoo_doctor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=200, null=True)),
                ('street2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('odoo_hq_id', models.IntegerField()),
                ('ppp_reference', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_hq_id', models.IntegerField()),
                ('hq_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AR', 'After'), ('BE', 'Before')], default='AR', max_length=2)),
                ('status', models.CharField(choices=[('DR', 'Submitted'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='DR', max_length=2)),
                ('ppp_date', models.DateTimeField(verbose_name='PPP date')),
                ('odoo_asm_id', models.IntegerField()),
                ('odoo_mr_id', models.IntegerField()),
                ('odoo_hq_id', models.IntegerField()),
                ('odoo_doctor_id', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('promotional_activity', models.CharField(max_length=200, null=True)),
                ('period', models.CharField(max_length=200, null=True)),
                ('promotional_expenses', models.CharField(max_length=200, null=True)),
                ('disbursement_nature', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPPLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_product_id', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ppp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.PPP')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_mr_id', models.IntegerField()),
                ('mr_name', models.CharField(max_length=200)),
                ('odoo_asm_id', models.IntegerField()),
                ('asm_name', models.CharField(max_length=200)),
                ('odoo_rsm_id', models.IntegerField(null=True)),
                ('rsm_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_stockist_id', models.IntegerField()),
                ('stockist_name', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=200, null=True)),
                ('street2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockistLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_hq_id', models.IntegerField()),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Stockist')),
            ],
        ),
    ]
