# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockistline',
            name='stockist',
        ),
        migrations.AddField(
            model_name='stockistline',
            name='odoo_stockist_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
