# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20160323_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemist',
            name='odoo_doctor_id',
            field=models.IntegerField(null=True),
        ),
    ]
